import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { LoginPage } from '../components/login-page'
import { useState } from 'react';
import HomePage from '../components/home-page';
import { isLoggedIn} from '../lib/fake-data';
import { useUser } from '@auth0/nextjs-auth0';
import { clientPromise } from '../lib/mongodb';

export async function getServerSideProps(context) {
  console.log("TESTING")
  try {
    await clientPromise
    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error("this is the error" + e)
    return {
      props: { isConnected: false },
    }
  }
}


export default function Home({isConnected}) {
  const { user, error, isLoading } = useUser();
 
  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  return (

    <div className={styles.container}>
      
      <div>{"IS CONNECTED" + isConnected}</div>
      <Head>
        <title>gnome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {!user && <LoginPage />}
      {user && <HomePage />}
    </div>
  )
}
