import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { LoginPage } from '../components/login-page'
import { useState } from 'react';
import HomePage from '../components/home-page';
import { isLoggedIn} from '../lib/fake-data';



export default function Home() {
 

  return (
    <div className={styles.container}>
      
      <Head>
        <title>gnome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {!isLoggedIn() && <LoginPage />}
      {isLoggedIn() && <HomePage />}
    </div>
  )
}
